[package]
name = "jsonnet"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
string-builder = "0.2.0"
unicode-segmentation = "1.12.0"
serde_json = "1.0.137"
